### ISSUE TITLE
Make sure package does not depend on itself

### ISSUE THREAD

**Issue by fredrikekre** [JuliaComputing/Registrator.jl#125]
Registrator should make sure that there is no package with the same name as the package itself under [deps], see https://github.com/JuliaRegistries/General/pull/230 and linked issues.

**Comment by nkottary** [comment]
Fixed in 648b49757f8d2a1f9a083b9b4c66246d7c4bb445

**Comment by schillic** [comment]
Is it not allowed to have the package as a weakdep of itself? I am trying to register a new version of a package where I applied that change and it gets rejected with the message

> Error while trying to register: Package X mentions itself in `[deps]`

even though it is not mentioned in `[deps]` (only in `[weakdeps]`).

**Comment by GunnarFarneback** [comment]
What is the use case for having a package weakly depending on itself?

**Comment by schillic** [comment]
Whether there is a use case, I am not sure. I originally tried this out because it seemed useful when having submodules `X.A`, `X.B` that each have a few method extensions that require the respective other submodule. So a standard case for weakdeps if `A` and `B` were standalone. And I wanted to collect these method extensions in a weakdep module to express that they belong to `A` and `B` in spirit. So my motivation was purely aesthetic. But since `A` and `B` live in `X`, this is of course not required and you can simply define these method extensions after defining `X.A` and `X.B` (for instance in another submodule `X.AB`). This is what I ended up doing to move on.

Let me add that the compiler accepts `X` being a weakdep of `X` without complaining.

Consider this a bug report that the error message is not precise.

**Comment by GunnarFarneback** [comment]
The message comes from https://github.com/JuliaRegistries/RegistryTools.jl/blob/master/src/register.jl#L106.
