### ISSUE TITLE
experience from trying out the process

### ISSUE THREAD

**Issue by tpapp** [JuliaComputing/Registrator.jl#46]
Thanks for all the great work. I [tried registering a package](https://github.com/tpapp/ContinuousTimeMarkov.jl/issues/6), here are some suggestions:

1. README should clarify that the user should [install the relevant app, currently RegistratorTest app](https://github.com/apps/registratortest/installations/new)

2. It would be great if commands did not have to be quoted with `` (like bors), if that is necessary for some reason, please clarify in the README.

3. It is unclear if (a) issue edits or (b) issue comments trigger the bot. Experimentally, comments seem to work.

4. I suspect that tagging a new version should be triggered the same as registering, please clariy this. In general, please add some detailed suggestions about version/release management, as various ideas were [discussed](https://github.com/JuliaLang/Pkg.jl/issues/849) and it may not be clear which one ended up being implemented.

**Comment by nkottary** [comment]
It was discussed earlier somewhere that tags/releases wouldn't be the best way to register because if there are problems, like in some cases project file is missing or incomplete then a new tag and release is required for triggering registration.

The other thing is that tags and releases are not really required for the Pkg system since all version info is contained in Versions.toml. So tags and releases can be decoupled from this process. Also note that the same tag/release can go to multiple registries so (i think) it shouldn't be tied to the registration process.

**Comment by nkottary** [comment]
Registrator's README as well as https://juliaregistrator.github.io both mention "Click here to install" in the beginning. I thought you might have missed that.

**Comment by tpapp** [comment]
Yes, I missed it, maybe a button like this could help?

https://img.shields.io/badge/-install%20app-blue.svg

**Comment by nkottary** [comment]
Yup, good idea.

**Comment by nkottary** [comment]
The new README.md should clarify this issue.
