### ISSUE TITLE
[FR] Allow tagging by adding a comment to a commit

### ISSUE THREAD

**Issue by Datseris** [JuliaComputing/Registrator.jl#59]
This will be convenient. You make a commit locally, with title whatever you want and with comment body "@JuliaRegistrator register()". And then when you push, the registrator does its job without you having to open your mozilla firefox or chrome or etc.

**Comment by StefanKarpinski** [comment]
I hate this kind of interface. The commit message is supposed to be a permanent log of changes to the code, not a bad UI for talking to bots and services. What happens if the registration request fails and this version doesn't end up being the actual release? Then you have `@JuliaRegistrator register()` in the commit message forever even though that wasn't the actual commit. Let's not encourage people to have junk messages with stuff in it like `@JuliaRegistrator register()` and `[ci skip]` and messages for whatever other integration thought it was a good idea to be controlled by commit messages.

**Comment by Datseris** [comment]
Fair enough.
